remote_theme: lekstm/jekyll-theme-console

title: 'lekstm.github.io'
#description: ""
#baseurl: "/jekyll-theme-console-dark"
#url: "https://lekstm.github.io"

header_pages:
  - index.md
  - works.md
  - about.md
  - contact.md

style: dark

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
#markdown: kramdown
#remote_theme: lekstm/jekyll-theme-console
